["6 SHORE ROAD",
"7 For All Mankind",
"Acacia Swimwear",
"adidas by Stella McCartney",
"AG Adriano Goldschmied",
"Alice + Olivia",
"Amanda Uprichard",
"American Vintage",
"ANINE BING",
"AQ/AQ",
"Bailey 44",
"BB Dakota",
"BCBGeneration",
"BCBGMAXAZRIA",
"BEC&BRIDGE",
"BLANKNYC",
"Blue Life",
"Bobi",
"Brian Lichtenberg",
"Canada Goose",
"Chaser",
"Cheap Monday",
"Citizens of Humanity",
"Clover Canyon",
"Current/Elliott",
"Diane von Furstenberg",
"Dolce Vita",
"eberjey",
"Eight Sixty",
"Elizabeth and James",
"Equipment",
"Finders Keepers",
"For Love & Lemons",
"Free People",
"Frye",
"G-Star",
"Haute Hippie",
"Hudson Jeans",
"Indah",
"J Brand",
"James Perse",
"Jeffrey Campbell",
"Jen's Pirate Booty",
"Joe's Jeans",
"Joie",
"Karen Walker",
"keepsake",
"LA Made",
"Lauren Moshi",
"Lovers + Friends",
"Mackage",
"Mara Hoffman",
"Marc by Marc Jacobs",
"McQ Alexander McQueen",
"MIKOH",
"MILLY",
"MINKPINK",
"MOTHER",
"NBD",
"One Teaspoon",
"Paige Denim",
"Parker",
"Rachel Pally",
"rag & bone/JEAN",
"Rails",
"Ray-Ban",
"Rebecca Minkoff",
"Rebecca Taylor",
"Riller & Fount",
"Siwy",
"Splendid",
"STONE_COLD_FOX",
"Stuart Weitzman",
"STYLESTALKER",
"Susana Monaco",
"T by Alexander Wang",
"T-Bags LosAngeles",
"Three Floor",
"Tibi",
"Tolani",
"Tularosa",
"UNIF",
"Velvet by Graham & Spencer",
"Wildfox Couture"]
